"""
Constants used in the project.
"""

LISTOFALLFORMS = "../data/list_of_noun_forms_full.csv"
BINARYMATRIX = "../data/matrix_of_syncr.csv"
CASE2LABEL = "../data/case2label.json"
INDEX2CASE = "../data/index2case.json"
GOLDLABELS2D = "../data/gold_labels_2d.pkl"
GOLDFORMS2D = "../data/gold_forms_2d.pkl"
GOLDLABELS1D = "../data/gold_labels_1d.npy"
FOLDFORMS1D = "../data/gold_forms_1d.npy"
FASTTEXTMODEL = "../data/final-model.bin"
VECTORSOUT = "../data/nonsynchr_casevectors.npy"
NOCLUCONFIG = "../data/config_files/noclu.config"
PCATSNECONFIG = "../data/config_files/pca_tsne.config"
RESULTCSV = "../data/result.csv"
FLOWDICTOUT = "../data/flow_dictionaries/"
DIMREDOUT = "../data/dim_reduced_input/nonsynchr_"
PCA215TSNE2 = "../data/dim_reduced_input/nonsynchr_pcatsne_215_2.npy"
PCA215TSNE3 = "../data/dim_reduced_input/nonsynchr_pcatsne_215_3.npy"
PCA277TSNE2 = "../data/dim_reduced_input/nonsynchr_pcatsne_277_2.npy"
PCA277TSNE3 = "../data/dim_reduced_input/nonsynchr_pcatsne_277_3.npy"
FIGURESOUT = "../figures/"
